#!/usr/bin/env python3
"""
Export the live catalog (items + shops) from the DB to versioned data/ files.

The shops and the bulk of the item catalog were imported straight into the live
DB (import_shops.py / import_bank_items.py) and existed *only* there — a fresh
seed.run() couldn't reproduce them. This dumps the authoritative DB state into
data/items.json + data/shops.json so the repo is the source of truth again and a
rebuild restores exactly what's live.

Run against the authoritative DB (on the VM, with .pg.env sourced, that's Postgres):
    python server/export_catalog.py
"""
import json
import pathlib

import db

DATA = pathlib.Path(__file__).resolve().parent.parent / "data"
DEV_SHOP_ID = 2722          # generated by fill_dev_shop.py from the catalog — not authored content


def main():
    with db.connect() as conn:
        items = {}
        for r in conn.execute("SELECT item_id FROM items ORDER BY item_id").fetchall():
            items[str(r["item_id"])] = db.item(conn, r["item_id"])

        shops = {}
        for s in conn.execute("SELECT shop_id FROM shops WHERE shop_id<>? ORDER BY shop_id",
                              (DEV_SHOP_ID,)).fetchall():
            links = [
                {"shop_item_id": li["shop_item_id"], "item_id": li["item_id"],
                 "cost": li["cost"], "coins": li["coins"], "quantity_remain": li["quantity_remain"]}
                for li in conn.execute(
                    "SELECT shop_item_id, item_id, cost, coins, quantity_remain "
                    "FROM shop_items WHERE shop_id=? ORDER BY shop_item_id", (s["shop_id"],)).fetchall()
            ]
            shops[str(s["shop_id"])] = {"meta": db.shop_blob(conn, s["shop_id"]), "items": links}

        cutscenes = {str(r["id"]): r["raw"]
                     for r in conn.execute("SELECT id, raw FROM cutscenes ORDER BY id").fetchall()}

    (DATA / "items.json").write_text(json.dumps(items, separators=(",", ":")), encoding="utf-8")
    (DATA / "shops.json").write_text(json.dumps(shops, separators=(",", ":")), encoding="utf-8")
    (DATA / "cutscenes.json").write_text(json.dumps(cutscenes, separators=(",", ":")), encoding="utf-8")
    links = sum(len(v["items"]) for v in shops.values())
    print(f"[export] data/items.json: {len(items)} items")
    print(f"[export] data/shops.json: {len(shops)} shops, {links} shop_item links "
          f"(dev shop {DEV_SHOP_ID} excluded — regenerate with fill_dev_shop.py)")
    print(f"[export] data/cutscenes.json: {len(cutscenes)} cutscenes")


if __name__ == "__main__":
    main()
